### ISSUE TITLE
Доработки

### ISSUE THREAD

**Issue by alexkoss** [rhino10001/group-analyzer#1]
Добрый день, @rhino10001 !
Меня зовут Александр, представитель Уно-Софт.
Предоставляю обратную связь по выполненному тестовому заданию:
Был ли проведён тест на большом входном файле https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z ?
Если да - какое время выполнения?

**Comment by rhino10001** [comment]
Добрый день! Да, тест проводил наилучшее время было 65 секунд (после нескольких запусков).
Наихудшее, что я у себя видел - 95 секунд.
Результат случайного запуска, проведенного только что:

> PS C:\Users\Rhino10001\Desktop\Новая папка\v3> java -jar -Xmx1G GroupAnalyzerV3.jar lng-big.csv
> Start time: 2023-08-07T14:31:35.438332200
> ...
> Finish time 2023-08-07T14:32:54.115989100
> 
> Total memory, (MB): 869
> Max memory, (MB): 1024
> Free memory, (MB): 303
> Memory usage, (MB): 565
> Duration, (s): 78.708

Запуск производился на процессоре Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz

**Comment by alexkoss** [comment]
@rhino10001 предлагаю обратиться к исходному заданию и прочитать его ещё раз, конкретнее - 60 строка https://github.com/PeacockTeam/new-job/blob/master/lng%26java#L60C40-L60C40

Приемлемое время выполнения - до 30 секунд. 

Жду доработок алгоритма.

**Comment by rhino10001** [comment]
В тексте задания, на которое Вы ссылаетесь, говорится о маленьком файле (на 1 млн строк) https://github.com/PeacockTeam/new-job/blob/2d874a83d1fc0d10e3d227d73275eff9afe8dbe7/lng%26java#L2.
Время выполнения для этого файла составляет 15 - 17 секунд.

**Comment by alexkoss** [comment]
Есть опыт других соискателей - до 30 секунд на большом файле. Будете дорабатывать алгоритм?

**Comment by rhino10001** [comment]
Попробую что-нибудь придумать

**Comment by rhino10001** [comment]
Добрый день! Я выполнил доработку

**Comment by alexkoss** [comment]
@rhino10001 добрый день. Какое время выполнения?

**Comment by rhino10001** [comment]
@alexkoss 12 для маленького, 8 для большого
